packages:
  - "apps/*"
  - "packages/*"
  - "infra/cdk"

linkWorkspacePackages: true

allowBuilds:
  canvas: true
  esbuild: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
