import type { Bundle, MarkupRule, PrintTemplate, Product } from "./types";

export const productCatalog: Product[] = [
  {
    slug: "die-cut-stickers",
    name: "Die-cut stickers",
    category: "stickers",
    description: "Custom contour stickers for laptops, water bottles, mailers, and creator drop extras.",
    popularUseCases: ["merch drops", "giveaways", "packaging extras"],
    baseQuantity: 100,
    startingPriceCents: 3900,
    dimensions: [{ label: "3 x 3 in", widthIn: 3, heightIn: 3 }],
    providerMappings: [{ provider: "4over", productCode: "TODO_REAL_4OVER_CODE", notes: "Map in admin when docs are available." }],
  },
  {
    slug: "roll-labels",
    name: "Roll labels",
    category: "labels",
    description: "Creator-ready product labels for beauty, food, candles, and packaging.",
    popularUseCases: ["beauty brands", "packaging", "limited runs"],
    baseQuantity: 250,
    startingPriceCents: 4500,
    dimensions: [{ label: "2 x 2 in", widthIn: 2, heightIn: 2 }],
    providerMappings: [{ provider: "4over", productCode: "TODO_REAL_4OVER_CODE" }],
  },
  {
    slug: "business-creator-cards",
    name: "Business/creator cards",
    category: "cards",
    description: "Pocket-sized brand cards with social handles, QR CTAs, and creator offers.",
    popularUseCases: ["networking", "meetups", "events"],
    baseQuantity: 250,
    startingPriceCents: 2900,
    dimensions: [{ label: "3.5 x 2 in", widthIn: 3.5, heightIn: 2 }],
    providerMappings: [{ provider: "4over", productCode: "TODO_REAL_4OVER_CODE" }],
  },
  {
    slug: "postcards",
    name: "Postcards",
    category: "mailers",
    description: "Drop announcements, thank-you cards, show invites, and branded mailers.",
    popularUseCases: ["mail drops", "events", "album launches"],
    baseQuantity: 250,
    startingPriceCents: 4900,
    dimensions: [{ label: "4 x 6 in", widthIn: 4, heightIn: 6 }],
    providerMappings: [{ provider: "4over", productCode: "TODO_REAL_4OVER_CODE" }],
  },
  {
    slug: "flyers",
    name: "Flyers",
    category: "flyers",
    description: "Fast promo flyers for events, menus, launch parties, and creator services.",
    popularUseCases: ["event promoters", "pop-ups", "local campaigns"],
    baseQuantity: 500,
    startingPriceCents: 6900,
    dimensions: [{ label: "8.5 x 11 in", widthIn: 8.5, heightIn: 11 }],
    providerMappings: [{ provider: "4over", productCode: "TODO_REAL_4OVER_CODE" }],
  },
  {
    slug: "posters",
    name: "Posters",
    category: "posters",
    description: "Short-run posters for shows, drops, signings, and in-store creator displays.",
    popularUseCases: ["musicians", "events", "retail displays"],
    baseQuantity: 10,
    startingPriceCents: 7900,
    dimensions: [{ label: "18 x 24 in", widthIn: 18, heightIn: 24 }],
    providerMappings: [{ provider: "4over", productCode: "TODO_REAL_4OVER_CODE" }],
  },
  {
    slug: "banners",
    name: "Banners",
    category: "banners",
    description: "Durable event and booth banners for drops, markets, shows, and meetups.",
    popularUseCases: ["events", "markets", "booths"],
    baseQuantity: 1,
    startingPriceCents: 8900,
    dimensions: [{ label: "2 x 6 ft", widthIn: 24, heightIn: 72 }],
    providerMappings: [{ provider: "4over", productCode: "TODO_REAL_4OVER_CODE" }],
  },
  {
    slug: "thank-you-insert-cards",
    name: "Thank-you insert cards",
    category: "inserts",
    description: "Small cards that turn each order into a social follow, review, or return visit.",
    popularUseCases: ["shipments", "reviews", "community building"],
    baseQuantity: 250,
    startingPriceCents: 3500,
    dimensions: [{ label: "3.5 x 5 in", widthIn: 3.5, heightIn: 5 }],
    providerMappings: [{ provider: "4over", productCode: "TODO_REAL_4OVER_CODE" }],
  },
  {
    slug: "qr-creator-cards",
    name: "QR creator cards",
    category: "cards",
    description: "Cards built around a QR CTA for link-in-bio, music, podcasts, menus, or shops.",
    popularUseCases: ["QR campaigns", "podcasts", "music links"],
    baseQuantity: 250,
    startingPriceCents: 2900,
    dimensions: [{ label: "3.5 x 2 in", widthIn: 3.5, heightIn: 2 }],
    providerMappings: [{ provider: "4over", productCode: "TODO_REAL_4OVER_CODE" }],
  },
  {
    slug: "packaging-labels",
    name: "Packaging labels",
    category: "packaging",
    description: "Box, mailer, jar, and pouch labels for creator shops and small brands.",
    popularUseCases: ["ecommerce", "beauty brands", "subscription boxes"],
    baseQuantity: 250,
    startingPriceCents: 4200,
    dimensions: [{ label: "3 x 2 in", widthIn: 3, heightIn: 2 }],
    providerMappings: [{ provider: "4over", productCode: "TODO_REAL_4OVER_CODE" }],
  },
];

export const templates: PrintTemplate[] = [
  {
    id: "tpl-sticker-bold-face",
    name: "Bold Face Sticker",
    productSlug: "die-cut-stickers",
    widthIn: 3,
    heightIn: 3,
    dpi: 300,
    bleedIn: 0.125,
    safeZoneIn: 0.125,
    backgroundColor: "#ffffff",
    slots: [
      { id: "hero-art", type: "image", x: 120, y: 80, width: 660, height: 620 },
      { id: "handle", type: "text", x: 170, y: 720, width: 560, height: 72, defaultValue: "@yourhandle" },
    ],
    providerHints: { provider: "4over", productCode: "TODO_REAL_4OVER_CODE" },
  },
  {
    id: "tpl-label-beauty-drop",
    name: "Beauty Drop Label",
    productSlug: "roll-labels",
    widthIn: 2,
    heightIn: 2,
    dpi: 300,
    bleedIn: 0.125,
    safeZoneIn: 0.1,
    backgroundColor: "#f8fff1",
    slots: [
      { id: "brand", type: "text", x: 80, y: 80, width: 440, height: 90, defaultValue: "Brand Name" },
      { id: "shape", type: "shape", x: 140, y: 200, width: 320, height: 260 },
    ],
    providerHints: { provider: "4over", productCode: "TODO_REAL_4OVER_CODE" },
  },
  {
    id: "tpl-card-link-in-bio",
    name: "Link-in-Bio Card",
    productSlug: "business-creator-cards",
    widthIn: 3.5,
    heightIn: 2,
    dpi: 300,
    bleedIn: 0.125,
    safeZoneIn: 0.125,
    backgroundColor: "#071018",
    slots: [
      { id: "name", type: "text", x: 80, y: 80, width: 620, height: 72, defaultValue: "Creator Name" },
      { id: "qr", type: "qr", x: 760, y: 110, width: 190, height: 190, defaultValue: "https://example.com" },
    ],
    providerHints: { provider: "4over", productCode: "TODO_REAL_4OVER_CODE" },
  },
  {
    id: "tpl-postcard-launch-note",
    name: "Launch Note Postcard",
    productSlug: "postcards",
    widthIn: 4,
    heightIn: 6,
    dpi: 300,
    bleedIn: 0.125,
    safeZoneIn: 0.125,
    backgroundColor: "#ffffff",
    slots: [
      { id: "image", type: "image", x: 120, y: 120, width: 960, height: 960 },
      { id: "copy", type: "text", x: 120, y: 1140, width: 960, height: 260, defaultValue: "Thanks for being part of the drop." },
    ],
    providerHints: { provider: "4over", productCode: "TODO_REAL_4OVER_CODE" },
  },
  {
    id: "tpl-flyer-pop-up",
    name: "Pop-up Flyer",
    productSlug: "flyers",
    widthIn: 8.5,
    heightIn: 11,
    dpi: 300,
    bleedIn: 0.125,
    safeZoneIn: 0.25,
    backgroundColor: "#f4fbff",
    slots: [
      { id: "headline", type: "text", x: 220, y: 220, width: 2100, height: 260, defaultValue: "Launch Party" },
      { id: "image", type: "image", x: 220, y: 560, width: 2100, height: 1700 },
      { id: "qr", type: "qr", x: 1990, y: 2820, width: 320, height: 320, defaultValue: "https://example.com" },
    ],
    providerHints: { provider: "4over", productCode: "TODO_REAL_4OVER_CODE" },
  },
  {
    id: "tpl-poster-music-night",
    name: "Music Night Poster",
    productSlug: "posters",
    widthIn: 18,
    heightIn: 24,
    dpi: 300,
    bleedIn: 0.125,
    safeZoneIn: 0.25,
    backgroundColor: "#101820",
    slots: [
      { id: "title", type: "text", x: 420, y: 520, width: 4560, height: 720, defaultValue: "Tonight Live" },
      { id: "poster-art", type: "image", x: 720, y: 1440, width: 3960, height: 4200 },
    ],
    providerHints: { provider: "4over", productCode: "TODO_REAL_4OVER_CODE" },
  },
  {
    id: "tpl-banner-drop-zone",
    name: "Drop Zone Banner",
    productSlug: "banners",
    widthIn: 24,
    heightIn: 72,
    dpi: 150,
    bleedIn: 0.25,
    safeZoneIn: 0.5,
    backgroundColor: "#ffffff",
    slots: [
      { id: "brand", type: "text", x: 360, y: 500, width: 2880, height: 340, defaultValue: "Creator Drop" },
      { id: "cta", type: "text", x: 360, y: 9300, width: 2880, height: 300, defaultValue: "Scan to shop" },
      { id: "qr", type: "qr", x: 1320, y: 10000, width: 960, height: 960, defaultValue: "https://example.com" },
    ],
    providerHints: { provider: "4over", productCode: "TODO_REAL_4OVER_CODE" },
  },
  {
    id: "tpl-insert-unboxing",
    name: "Unboxing Thank You",
    productSlug: "thank-you-insert-cards",
    widthIn: 3.5,
    heightIn: 5,
    dpi: 300,
    bleedIn: 0.125,
    safeZoneIn: 0.125,
    backgroundColor: "#fffaf0",
    slots: [
      { id: "message", type: "text", x: 120, y: 150, width: 810, height: 540, defaultValue: "Your support means everything." },
      { id: "handle", type: "text", x: 120, y: 1180, width: 810, height: 90, defaultValue: "@yourhandle" },
    ],
    providerHints: { provider: "4over", productCode: "TODO_REAL_4OVER_CODE" },
  },
  {
    id: "tpl-qr-podcast-card",
    name: "Podcast QR Card",
    productSlug: "qr-creator-cards",
    widthIn: 3.5,
    heightIn: 2,
    dpi: 300,
    bleedIn: 0.125,
    safeZoneIn: 0.125,
    backgroundColor: "#ecfeff",
    slots: [
      { id: "title", type: "text", x: 80, y: 80, width: 590, height: 120, defaultValue: "Listen now" },
      { id: "qr", type: "qr", x: 760, y: 90, width: 220, height: 220, defaultValue: "https://example.com/podcast" },
    ],
    providerHints: { provider: "4over", productCode: "TODO_REAL_4OVER_CODE" },
  },
  {
    id: "tpl-packaging-clean-seal",
    name: "Clean Seal Label",
    productSlug: "packaging-labels",
    widthIn: 3,
    heightIn: 2,
    dpi: 300,
    bleedIn: 0.125,
    safeZoneIn: 0.125,
    backgroundColor: "#ffffff",
    slots: [
      { id: "logo", type: "text", x: 90, y: 90, width: 720, height: 120, defaultValue: "Drop Label" },
      { id: "art", type: "shape", x: 110, y: 250, width: 680, height: 210 },
    ],
    providerHints: { provider: "4over", productCode: "TODO_REAL_4OVER_CODE" },
  },
];

export const creatorDropKit: Bundle = {
  id: "creator-drop-kit",
  name: "Creator Drop Kit",
  description: "A launch bundle for creator merch drops, unboxings, QR discovery, and social promo.",
  items: [
    { productSlug: "die-cut-stickers", quantity: 100 },
    { productSlug: "qr-creator-cards", quantity: 250 },
    { productSlug: "thank-you-insert-cards", quantity: 250 },
    { productSlug: "packaging-labels", quantity: 250 },
    { productSlug: "posters", quantity: 10, optional: true },
    { productSlug: "banners", quantity: 1, optional: true },
  ],
};

export const markupRules: MarkupRule[] = [
  { productSlug: "die-cut-stickers", percentage: 35, minimumMarginCents: 900 },
  { productSlug: "qr-creator-cards", percentage: 32, minimumMarginCents: 800 },
  { productSlug: "thank-you-insert-cards", percentage: 34, minimumMarginCents: 900 },
  { productSlug: "packaging-labels", percentage: 34, minimumMarginCents: 900 },
  { productSlug: "postcards", percentage: 35, minimumMarginCents: 1000 },
  { productSlug: "flyers", percentage: 30, minimumMarginCents: 1200 },
  { productSlug: "posters", percentage: 35, minimumMarginCents: 1600 },
  { productSlug: "banners", percentage: 30, minimumMarginCents: 2000 },
];

export function getProductBySlug(slug: string): Product | undefined {
  return productCatalog.find((product) => product.slug === slug);
}

export function getTemplateById(id: string): PrintTemplate | undefined {
  return templates.find((template) => template.id === id);
}

export function getTemplatesByProduct(productSlug: string): PrintTemplate[] {
  return templates.filter((template) => template.productSlug === productSlug);
}
